### ISSUE TITLE
Better i18n support

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#101]
Feedback from a user in the Advent of Code challenge:

> Somewhat confusing that the interface is English, whereas the error messages are in Dutch :)

**Comment by boegel** [comment]
I happen to know the user @pdawyndt is referring to...

Example:

![Screenshot 2020-12-01 at 20 27 53](https://user-images.githubusercontent.com/620876/100787329-c3dd1100-3413-11eb-8580-247c4fe40c15.png)
