### ISSUE TITLE
Kotlin is slow

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#102]
Kotlin submissions take pretty long to process. Most don't get through the time limit, where other languages seem to have no issues.

**Comment by bsels** [comment]
A first explanation is the long compilation time for Kotlin even for very simple programs like Hello World, when comparing to Java.

Java:
```java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}
```
Compile time `1.301 s`:
```console
$ time javac HelloWorld.java 

real	0m0.393s
user	0m0.860s
sys	0m0.048s
```

Kotlin:
```kotlin
fun main() {
    println("Hello world");
}

```
Compile time `8.188 s`:
```console
$ time kotlinc HelloWorld.kt 

real	0m2.230s
user	0m5.715s
sys	0m0.242s
```

**Comment by bsels** [comment]
There is not much difference in execution time between Java and Kotlin.
The time difference could be explained by small changes in system load.

Java `0.134 s`:
```console
$ time java HelloWorld
Hello world

real	0m0,054s
user	0m0,043s
sys	0m0,037s
```
Kotlin `0.179 s`:
```console
$ time kotlin HelloWorldKt
Hello world

real	0m0.076s
user	0m0.069s
sys	0m0.034s
```

**Comment by bsels** [comment]
```bash
$ kotlinc -Xreport-perf HelloWorld.kt
info: PERF: INIT: Compiler initialized in 661 ms
info: PERF: ANALYZE: 1 files (3 lines) in targets [main-java-production]in 720 ms - 4,167 loc/s
info: PERF: GENERATE: 1 files (3 lines) target main-java-production in 91 ms - 32,967 loc/s
info: PERF: GC time for G1 Young Generation is 86 ms
info: PERF: GC time for G1 Old Generation is 0 ms
info: PERF: JIT time is 3826 ms
info: PERF: Find Java class performed 1 times, total time 0 ms
info: PERF: Type info performed 4 times, total time 305 ms
info: PERF: Call resolve performed 1 times, total time 268 ms
info: PERF: Binary class from Kotlin file performed 110 times, total time 42 ms
```

**Comment by niknetniko** [comment]
Three years later and the situation has not improved. Since there is no real other way of running Kotlin besides `kotlinc` if we don't want a full Gradle solution, there is not much we can do here.

There are a few issues about it upstream, but not much activity: https://youtrack.jetbrains.com/issue/KT-32817, https://youtrack.jetbrains.com/issue/KT-19667, https://youtrack.jetbrains.com/issue/KT-52460 (this last one is basically our scenario)
