### ISSUE TITLE
JavaScript issue

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#103]
Worth investigating what the problem is with https://dodona.ugent.be/nl/submissions/6602174/#code.

The code:

```javascript
isValidPassword = (password, policy) => {
    var policyMatch = policy.match(/(\d+)-(\d+) (\w)/);
    var [min, max, policyChar] = [policyMatch[1], policyMatch[2], policyMatch[3]];
    var policyCharCount = (password.match(new RegExp(`${policyChar}`, 'g')) || []).length;

    return(policyCharCount >= min && policyCharCount <= max);
}
```

Results in:

> ReferenceError: isValidPassword is not defined

Probably/maybe has to do with the fact that the "function" is not defined as a function.

**Comment by pdawyndt** [comment]
![image](https://user-images.githubusercontent.com/5736113/100853817-7f3f8d00-3488-11eb-8704-6f84e5d9e768.png)

**Comment by pdawyndt** [comment]
Does not seem related to the fact that an arrow function was used. Also doesn't work if an anonymous function is assigned to a variable ([example](https://dodona.ugent.be/nl/submissions/6602309/)).

**Comment by niknetniko** [comment]
> Does not seem related to the fact that an arrow function was used. Also doesn't work if an anonymous function is assigned to a variable ([example](https://dodona.ugent.be/nl/submissions/6602309/)).

It does work when using `function name(...)`: https://dodona.ugent.be/nl/submissions/6602326/

This is because we now parse the javascript solutions in TESTed before we execute them, to prevent conflicts (before the code was just included). This is not ideal, as shown in this instance. Perhaps in the future we'll need to look into something like https://nodejs.org/api/vm.html, which could allow us to not parse.

**Comment by pdawyndt** [comment]
These VMs are also used by the JavaScript judge. Maybe good idea to have a look over there. My experience: good separation of judge from code submitted by user and tests and no observable impact on performance.
