### ISSUE TITLE
Link filenames in statements to file content

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#106]
Add option to link filenames in statements to file content (files in the description/media folder). This way, users can inspect the file content from the feedback table.

![image](https://user-images.githubusercontent.com/5736113/100986190-2a197f00-354d-11eb-8a43-a6e361be6bc5.png)
Example: [submission 6607997](https://dodona.ugent.be/en/submissions/6607997/)

Here's how the file content is displayed in the feedback table of the Python judge:

![image](https://user-images.githubusercontent.com/5736113/100986304-4d442e80-354d-11eb-98d6-6514ae50cc0f.png)
Example: [submission 6493363](https://dodona.ugent.be/en/submissions/6493363/)

**Comment by pdawyndt** [comment]
Instead of all files in `workdir` we could also put them in `evaluation` (e.g. `evaluation/workdir`). This would not make the files accessible by default (the `evaluation` dir is only accessible for the judge, not for the submitted code; should be treated as readonly). We could then "register" the files that are needed in a given context, which could server multiple purposes:

- copy only those files to the execution context (from `evaluation/workdir` or `workdir`); this would have the benefit that one context could not remove, change or tamper the files in a ways that influence other contexts
- on the feedback page: link filenames in statements to file content
- make files available e.g. to Python Tutor (future work)

**Comment by niknetniko** [comment]
To zoom in on "registering" the files, some possibilities I can think of:

- Include a list of files in the test plan in a special input (e.g. there is a fixed file or you don't want to work with arguments)
- Introduce a new "type" in the function arguments: "FileName".
   - Works with how we often do things (pass the "path" to the file as an argument)
   - Allows to annotate those params as a file for Dodona (I forget how this happens, but it will be cleaner than guessing which params are a file and which not)

Both could be supported at the same time.

**Comment by pdawyndt** [comment]
This is how it looks like in a testcase on the feedback table:

```html
<div class="testcase correct contains-file" data-files="{&quot;photo01.txt&quot;:{&quot;content&quot;:&quot;media/photo01.txt&quot;,&quot;location&quot;:&quot;href&quot;,&quot;name&quot;:&quot;photo01.txt&quot;,&quot;storage&quot;:&quot;disk&quot;}}"><div class="col-xs-12 description"><div class="indicator"><i class="mdi mdi-check mdi-18"></i></div><span class="code">coordinates('<a href="#" class="file-link">photo01.txt</a>')</span></div><div class="col-xs-12 test"><div class="description"><span class="label label-success">return</span></div><div class="test-accepted"><span class="output">{(0, 0), (1, 1), (0, 2)}</span></div></div><div class="col-xs-12"></div></div>
```

**Comment by pdawyndt** [comment]
Maybe we could also experiment with providing file links in a separate context-level message in the feedback table.
