### ISSUE TITLE
Wrong number of incorrect testcases

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#113]
Bag on tab shows wrong number of incorrect testcases. In [this tab](https://dodona.ugent.be/en/courses/414/series/4216/activities/912386004/), there are only 50 contexts, each having a single testcase. The last tab has only 20 contexts, each having a single testcase. Seems that testcases are counted twice.

![image](https://user-images.githubusercontent.com/5736113/101243465-de0f3b80-3700-11eb-965e-9ce0fff62588.png)

**Comment by pdawyndt** [comment]
I suggest that only the incorrect testcases are counted for the badge, not the wrong contexts.

**Comment by niknetniko** [comment]
I think this count is done by Dodona itself, TESTed doesn't do this

**Comment by pdawyndt** [comment]
Could be. There's an option to set the badge count explicitly in the feedback, but there could indeed be a default behaviour in Dodona itself (at least for a while, the default behaviour has been to have no badge count).

**Comment by niknetniko** [comment]
This seems to not have happened in a while, so I will assume it is fixed.
