### ISSUE TITLE
Better reporting of contexts/testcases that were not executed

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#114]
This is how TESTed represents a context with a single testcase that is not executed

![image](https://user-images.githubusercontent.com/5736113/101243519-40683c00-3701-11eb-92f1-2c1b1b16c79c.png)
Example: [submission 912386004](https://dodona.ugent.be/en/courses/414/series/4216/activities/912386004/)

- seems useless to indicate that both the context and each testcase in the context aren't executed
- looks weird to see a context with an empty description (because it has a message; maybe use message as description in this case; message should also tell that context has not been executed, not the testcase)
- best option would be that Dodona supports a "not executed" status, with a corresponding color (e.g. grey instead of red) and icon (but cross seems also valid in this case)

**Comment by pdawyndt** [comment]
This might use the status in Dodona for testcases that have not been processed (dodona-edu/dodona#1785; not available yet).

**Comment by bsels** [comment]
TODO:
[ ] Not executed message at context level
[ ] Empty description for context -> message = description
[ ] Use special status

**Comment by niknetniko** [comment]
We have done all we can, when or if Dodona adds support for the status, we'll add it in TESTed as well.
