### ISSUE TITLE
Kotlin: unexpected compiler error

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#117]
This [Kotlin solution](https://dodona.ugent.be/nl/submissions/6651099/) sometimes succeeds and gives a compiler error on other occasions.

**Comment by bsels** [comment]
I think it's a problem with running in the Docker Image on some worker servers, but I'm not sure.

Propably the same reason that Haskell get memory limits on some worker servers: https://www.javaer101.com/en/article/39078804.html.

**Comment by bsels** [comment]
Normal fixed in #226
