### ISSUE TITLE
Cleanup Exception trace python

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#140]
See https://dodona.ugent.be/activities/270198713/

**Comment by pdawyndt** [comment]
The first file reference line should be removed (as is refers to internal code of the judge). The second file reference line may be retained. In other judges, we even link this line to the corresponding line in the "Code" tab of the feedback (Dodona has support for this). We might consider replacing `'submission.py'` by `<code>`, as the name of the file itself is also internal to the judge.

![image](https://user-images.githubusercontent.com/5736113/107847893-99cea480-6def-11eb-9921-2a4ffcff2603.png)

**Comment by pdawyndt** [comment]
Also check why there's a double "uitvoeren code" in the feedback.

**Comment by bsels** [comment]
The double "uitvoeren code" cames from the context description and the testcase description

**Comment by bsels** [comment]
The stacktrace isn't cleaned because of the specific evaluator
