### ISSUE TITLE
Inline file links in python statements doesn't work

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#167]
See https://dodona.ugent.be/nl/submissions/7082650/

**Comment by pdawyndt** [comment]
@bsels: I would exclude the quotes around the filename from the anchor that links to the file.

**Comment by pdawyndt** [comment]
@bsels: The file link is now a pure link, but Dodona also supports a special link class that allows to show (part of) the file content in a popup window (with a download button). Maybe that's a cleaner option.

**Comment by bsels** [comment]
> @bsels: The file link is now a pure link, but Dodona also supports a special link class that allows to show (part of) the file content in a popup window (with a download button). Maybe that's a cleaner option.

I thought we already discussed this and that this is the functionality of the Python Tutor in the Pythia Judge, not of Dodona.
But if I'm mistaken what is the HTML class? Currently I use `file-link`.

**Comment by bsels** [comment]
> @bsels: I would exclude the quotes around the filename from the anchor that links to the file.

Suggestion applied
