### ISSUE TITLE
Method calls Java

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#175]
`void`-function raise a compilation error in the generated code.

**Comment by niknetniko** [comment]
There is some code remaining here (the `has_return` _should_ detect _methods_):

https://github.com/dodona-edu/universal-judge/blob/9ea7a4c1bc3059254f3e210cc56969dbcd97e2e7/tested/languages/generator.py#L310-L322

But I'm unsure if this is still used in the generators.

(also for clarity, I don't think methods have a `void` return type per definition, see https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html, it was my understanding a method is function on a object)

**Comment by bsels** [comment]
I have tested these `void` functions while expecting a `NothingType` and therefor it didn't work.
I will write an additional test, such that will also test that the `empty`/`ignore` channel for a functioncall.
