### ISSUE TITLE
Think about jars in repo

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#185]
There are now two jars in the repo (checkstyle & ktlint).

Ideally we don't want jars inside the repo, so determine:

- Why are they included as a jar? (@bsels)
- Are there alternatives?
- Advantages/disadvantages of each approach

**Comment by bsels** [comment]
[Checkstyle](https://github.com/checkstyle/checkstyle/releases/) is only available as JAR or source code.

**Comment by bsels** [comment]
[KTLint](https://github.com/pinterest/ktlint/releases/tag/0.41.0) Is available as JAR that can be runned as shell script.
But I tried adding it to executable path (`$PATH`), local this works but at Dodona this fails (see #182).
`$PATH` in Docker: `/usr/local/sdkman/candidates/kotlin/current/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

I try installing KTLint with, which succeeded:
```
$ curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint && chmod a+x ktlint && mv ktlint /usr/local/bin/
```

**Comment by niknetniko** [comment]
Valid reasons. As for the alternatives, I currently see two possibilities:

- In the far future, we might need to look into adding support for build systems for languages. This would allow us to use and/or provide packages for the various languages (and allow local use of the Haskell packages, which would make life a lot easier).

- More short term: both jars can be used on the command line, so it is possible to put the dependencies in the Dockerfile. Perhaps we can see how https://github.com/github/super-linter does it?

The last option does make it harder to run it locally, so we need to document this thoroughly (where and what needs to be on the path).
