### ISSUE TITLE
JavaScript Issues

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#202]
- [ ] Objects with invalid numbers: https://dodona.ugent.be/nl/submissions/7527539/
- [ ] Unknown type when having no returnvalue: https://dodona.ugent.be/nl/submissions/7527480/ (function not defined)

**Comment by bsels** [comment]
Discussion: what must the `undefined` type of JavaScript be in TESTed:
Currently `unknown` value is used, but I think it's better to repressent it with the `nothing` value.

**Comment by bsels** [comment]
Problem: `NaN` numbers are represented as `null` in JSON.
Possible solutions:
1) We could use JSON5 to represent these values.
2) Allow `null` values for numbers in the JSON, which will represent `NaN`values.
3) Represent them as `unknown` values.

**Comment by bsels** [comment]
4. Use an enum to represent `NaN`, `Infinity` and `-Infinity`. I think this is the best solution.

**Comment by niknetniko** [comment]
> Discussion: what must the `undefined` type of JavaScript be in TESTed:
> Currently `unknown` value is used, but I think it's better to repressent it with the `nothing` value.

We do lose the distinction between `undefined` and `null`, but I think this is acceptable, since this doesn't exist in a lot of languages.

> Problem: NaN numbers are represented as null in JSON.

We should be careful to introduce something that can also be used in other languages, not just JavaScript. However, this is mostly a "problem" on the language side in detecting NaN/-Infinity/+Infinity.

I think the enum is a good solution. One question remains: do we add support for this to all numerical types, or just a separate type, only advanced types or basic types?

- Support in the `*_precision` types is fairly obvious, as the IEEE 754 also supports this.
- Support in the basic type `rational` is perhaps needed for optimal compatibility between languages: I don't think there is a problem by supporting it here.
- I would not support it in the `integer` types.

So for example, 

```json
{
   "type": "rational",
   "value": "NaN"
}
```

**Comment by niknetniko** [comment]
> https://dodona.ugent.be/nl/submissions/7527539/

Perhaps for another issue, but I think the "wrong" return value should go through the type renderer, since it seems the internal structure is shown:

![image](https://user-images.githubusercontent.com/1756811/115389779-cfbc4a80-a1dd-11eb-81f4-9c7edfc6c3e3.png)

**Comment by bsels** [comment]
> Perhaps for another issue, but I think the "wrong" return value should go through the type renderer, since it seems the internal structure is shown:

This is the problem of the `NaN`, the result couldn't be parsed and then send to the type renderer.

> I think the enum is a good solution. One question remains: do we add support for this to all numerical types, or just a separate type, only advanced types or basic types?

Adding it to all numeric types doesn't seems a problem to me: because these concepts don't exists for integer types (which technical also could be a float in the JSON), this could be solved by an additional test for the JSON parser.
And it should be possible to supported it for all rational number types.

**Comment by chvp** [comment]
Losing the distinction between undefined and null seems like something we should want to avoid. I don't entirely get the problem though? Functions without a return statement return undefined in javascript, I don't think we need special handling for functions that explicitly return undefined or functions that don't have a return statement.

An enum for floats that can't be represented in JSON seems fine to me.

**Comment by bsels** [comment]
> Losing the distinction between undefined and null seems like something we should want to avoid. I don't entirely get the problem though?

The problem is that TESted will return `{"type": "unknown"}` for the `undefined` values with an additional message.

**Comment by niknetniko** [comment]
> The problem is that TESted will return `{"type": "unknown"}` for the `undefined` values with an additional message.

Couldn't this be fixed in the JavaScript implementation by not returning anything as return value if the function returns `undefined`?

**Comment by pdawyndt** [comment]
I don't like the repetition in the representation of an "unexpected exception" very much.

![image](https://user-images.githubusercontent.com/5736113/115396703-938ce800-a1e5-11eb-8978-2060a172a215.png)

Example: submission [7528170](https://dodona.ugent.be/nl/submissions/7528170/)

**Comment by niknetniko** [comment]
I have created separate issues for the multiple issues in this one, which makes discussing the issues easier. This also allows for separate PR's, which makes the reviewing easier.

If new issues arise, we should make a new issue in the repo instead of collecting everything here.
