### ISSUE TITLE
Handling NaN in TESTed

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#203]
From #202.

Problem: `NaN` numbers are represented as `null` in JSON.
Possible solutions:
1) We could use JSON5 to represent these values.
2) Allow `null` values for numbers in the JSON, which will represent `NaN`values.
3) Represent them as `unknown` values.
4) Use an enum to represent `NaN`, `Infinity` and `-Infinity`. I think this is the best solution.

**Comment by niknetniko** [comment]
> Problem: NaN numbers are represented as null in JSON.

We should be careful to introduce something that can also be used in other languages, not just JavaScript. However, this is mostly a "problem" on the language side in detecting NaN/-Infinity/+Infinity.

I think the enum is a good solution. One question remains: do we add support for this to all numerical types, or just a separate type, only advanced types or basic types?

- Support in the `*_precision` types is fairly obvious, as the IEEE 754 also supports this.
- Support in the basic type `rational` is perhaps needed for optimal compatibility between languages: I don't think there is a problem by supporting it here.
- I would not support it in the `integer` types.

So for example, 

```json
{
   "type": "rational",
   "value": "NaN"
}
```

**Comment by niknetniko** [comment]
Boris:

> 
> I think the enum is a good solution. One question remains: do we add support for this to all numerical types, or just a separate type, only advanced types or basic types?
> 
> Adding it to all numeric types doesn't seems a problem to me: because these concepts don't exists for integer types (which technical also could be a float in the JSON), this could be solved by an additional test for the JSON parser.
> And it should be possible to supported it for all rational number types.

**Comment by bsels** [comment]
For some programming languages `NaN` is supported for `fixed_precision` and `double_extended` for other programming languages not.
