### ISSUE TITLE
Handling undefined in TESTed

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#205]
See #202. Summary: TESTed doesn't support `undefined`, which is useful in JS.

**Comment by niknetniko** [comment]
To continue this issue: upon further reflection, I think adding `undefined` as an advanced type (with basic type `nothing`) is a better way of fixing this:

- If you explicitly want `undefined` as a return value, you probably want `None` in Python and `null` in Java (etc.), so this will take care of that.
- The expected value in the Dodona feedback will be correct (and not `null`).
- Testing functions without return value is still supported (since this is handled in the judge itself, not in the language implementations).

**Comment by chvp** [comment]
Sounds good to me.
