### ISSUE TITLE
References to linter rule information

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#210]

**Comment by niknetniko** [comment]
While we can implement this entirely on the judge side, perhaps it's an idea to consider adding support for this to Dodona if this is general enough, which would allow something like this:

![image](https://user-images.githubusercontent.com/1756811/115519416-7a3d7780-a289-11eb-8638-e7eac9279cc5.png)

(or perhaps just the icon without the text to make the page less busy)

**Comment by pdawyndt** [comment]
If Dodona doens't already have an issue for this, I would be in favor to create one.

**Comment by bsels** [comment]
@niknetniko It would only be necessary to add a link to the `annotate-code`-command.

**Comment by bsels** [comment]
> @niknetniko It would only be necessary to add a link to the `annotate-code`-command (from the judge side).

**Comment by pdawyndt** [comment]
@bsels Can you check which of the linters you use have more information online about the rules they apply?

**Comment by bsels** [comment]
- Bash: Shellcheck: `https://github.com/koalaman/shellcheck/wiki/<code>`
  Example: https://github.com/koalaman/shellcheck/wiki/SC2213
- C: CPPCheck: No documentation available
- Java: Checkstyle: `https://checkstyle.sourceforge.io/apidocs/index.html?<code>.html`
  Example: https://checkstyle.sourceforge.io/apidocs/index.html?com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.html
- JavaScript: ESLint: `https://eslint.org/docs/rules/<code>`
  Example: https://eslint.org/docs/rules/for-direction
- Kotlin: KTLint: No specific page for a rule: https://ktlint.github.io/#rules
- Haskell: HLint: No specific page for a rule: https://github.com/ndmitchell/hlint/blob/master/hints.md
- Python: PYLint: No specific page for a rule: https://docs.pylint.org/en/1.6.0/features.html

**Comment by pdawyndt** [comment]
Kotlin allows in-page links (e.g. [https://ktlint.github.io/#rule-spacing]), so that fine as well.

**Comment by pdawyndt** [comment]
Don't know if [this documentation](http://pylint-messages.wikidot.com/all-codes) is still up-to-date, but it has separate pages with more explanation for pylint messages.

**Comment by bsels** [comment]
> Don't know if [this documentation](http://pylint-messages.wikidot.com/all-codes) is still up-to-date, but it has separate pages with more explanation for pylint messages.

This documentation is outdated.

**Comment by bsels** [comment]
> Kotlin allows in-page links (e.g. https://ktlint.github.io/#rule-spacing), so that is fine as well.

Not all rules have a reference in KTLint.
