### ISSUE TITLE
Syntax error check prior to execution of interpreted languages

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#214]
This error message is not logical for student:

https://dodona.ugent.be/nl/submissions/7542435/

**Comment by bsels** [comment]
`TypeError: Cannot read property 'evenwichtig' of undefined`
The cause of this error is an invalid solution sourcecode that can't be analysed by `esprima`.

We could look to improve the error message.

**Comment by pdawyndt** [comment]
Would it be better to parse the JavaScript code (or any interpreted code) explicitly before trying to execute it in a language-specific testplan. I guess that TESTed catches syntax errors for compiled languages at compile time. For interpreted languages we'd better also do a syntax check before building the language-specific testpan, report syntax errors in a separate tab or as a top-level message (same way as TESTed reports compilation errors), and mark all tests in all other tabs as "not executed" in case of syntax errors.

**Comment by niknetniko** [comment]
I think the Python implementation already does this by "compiling" the code in the compilation step. Something similar exists for JS with the `--check` option: https://nodejs.org/api/cli.html#cli_c_check
