### ISSUE TITLE
Representation of multiline strings 

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#221]
Multiline strings as return values in the feedback are now represented as string literals (`"...\n...\n...\n..."`). There representation over multiple lines has some advantages:

- clearer representation for students
- easier to see the effect of diffing

It may also have the disadvantage that it's no explicitly clear that the return value is a string (ideally this should be represented somehow, e.g. in the label of the test `return (String)`, but that may again clutter the feedback table.

Experimenting with multiline strings shown in a multiline way have proven beneficial in the Python and JavaScript judges, so I would also recommend to apply this practice in TESTed.

**Comment by pdawyndt** [comment]
We also need a heuristic to determine when multiline strings are represented in a multiline way, e.g. if both the top-level types of the expected and generated return values are strings (not strings as part of a compound datastructure) and at least on of the two contains a newline character. Or do we make the decision for the expected and generated return values independently (which might again be confusion)?

Check which heuristics are used by the Python and JavaScript judges (can't remember).

**Comment by bsels** [comment]
In YAML you can represent multiline strings between quotes:
```
string: "Lijn1
Lijn2
Lijn3"
```
Maybe we can use this notation instead of  `return (String)`.
But `return (String)` is also a good idea.

**Comment by pdawyndt** [comment]
In YAML you effectively need the quotes as delimiters. In the representation they are merely clutter. Especially since multiline strings sometimes represent grids, and the extra starting delimiter break the alignment of the grid.

**Comment by bsels** [comment]
The repressentation in the JavaScript-judge is:
```js
expected: (
    multiline(expected_result) ? 
    expected_result : 
    utils.display(expected_result)
)
```
`utils.display(expected_result)` is just the `JSON.stringify` for strings.

The condtion is:
```js
function multiline(s) {
    return typeof s === "string" && s.includes("\n");
}
```
which only check if the object is a "string" which contains at least one newline character.

**Comment by niknetniko** [comment]
At least for the JSON, I would probably add an option to the value evaluator. To quote its docs:

> Currently, this evaluator has no options, but it might receive them in the future (e.g. options on how to deal with **strings** or floats).

In JSON, a return value would then be:

```
                  "output": {
                    "result": {
                      "value": {
                        "type": "text",
                        "data": "input-2\nhello"
                      },
                      "evaluator": {
                        "type": "builtin",
                        "options": {
                          "stringsAsText": true,
                        }
                      }
                    }
                  },
```

Where the `stringsAsText` option would not display it as `"contents of the string"`, but without the quotes, etc.

- If the option is set to `true`, we can then use the logic to determine when to use it (e.g. for all top-level string values).
- What should the default be? Show string return values as a string or not?
- In the DSL we might infer the option by using the heuristic, e.g. if the expected value has a newline or not.

**Comment by bsels** [comment]
Good idea to add the option in the JSON, but default I would enable this but the option could be used to disable this feature.
