### ISSUE TITLE
Support global variables from namespace

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#230]
- [x] Support in JSON
- [x] Support in DSL
- [x] Write tests

**Comment by bsels** [comment]
Idea how to add it in the JSON:
```python3
@dataclass
class GlobalIdentifier(WithFeatures, WithFunctions):
    """Class for global variables from the submission"""
    name: str
    """Name of the global variable"""
    is_function: bool = False
    """
    Indicates if the global variable is a function,
    required to conventionalize the function name and method-references in some
    programming languages
    """
    type: Literal['global'] = "global"

    def __post_init__(self):
        # Namespace must be add dynamic when generating the testcode
        self.namespace: Optional[str] = None

    def get_used_features(self) -> FeatureSet:
        if self.is_function:
            return FeatureSet({Construct.GLOBAL_FUNCTIONS_AS_VARIABLES}, set(),
                              set())
        else:
            return FeatureSet({Construct.GLOBAL_VARIABLES}, set(), set())

    def get_functions(self) -> Iterable['FunctionCall']:
        return []
```

**Comment by bsels** [comment]
In the DSL we could write: `::function_name` for a method reference.
A normal global variable we could notate with `<variable_name>`.

**Comment by bsels** [comment]
Maybe a better alternative for the method reference is adding a new type `REFERENCE` to the existing function calls for methods and functions.
And possible also `CONSTRUCTOR_REFERENCE` to reference constructors.

**Comment by bsels** [comment]
Maybe a better alternative for the global variables is using the `PROPERTY` function call without namespace.

**Comment by niknetniko** [comment]
> Maybe a better alternative for the global variables is using the `PROPERTY` function call without namespace.

I agree this is the most logical place to add this.
