### ISSUE TITLE
Rename exitCode as exit

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#266]
Rename the output channel simply as exit. Motivation: KISS

**Comment by chvp** [comment]
I'm not sure I agree. `exit` seems less clear to me than `exitCode`.

**Comment by bsels** [comment]
> I'm not sure I agree. `exit` seems less clear to me than `exitCode`.

I agree, `exitCode` is more clear for users that just read the testplan without reading the documentation.

**Comment by niknetniko** [comment]
After some more consideration, `exit_code` is the most clear term, so for now we'll keep it.
