### ISSUE TITLE
Type of empty arrays in Java

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#272]
This is the problem: Empty arrays are defined as object array's:
![dodona ugent be_nl_courses_637_series_7132_activities_541948398__from_solution=Sorteren java](https://user-images.githubusercontent.com/38499296/124260007-79e61600-db2f-11eb-8df0-1a708e2e126e.png)
But we probably want to define the type of the content of these arrays (in extension all the  inner types of the complex types), example:
![dodona ugent be_nl_courses_637_series_7132_activities_541948398__from_solution=Sorteren java](https://user-images.githubusercontent.com/38499296/124260460-01cc2000-db30-11eb-8e7c-c8bf83cb20d0.png)

**Comment by niknetniko** [comment]
Should be handled with #276
