### ISSUE TITLE
Broken link from traceback to code line

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#285]
Example submission: [9255483](https://dodona.ugent.be/nl/submissions/9255483/)

**Comment by pdawyndt** [comment]
Here's another submission where the link no longer works: https://dodona.ugent.be/nl/submissions/13723111/

**Comment by pdawyndt** [comment]
@niknetniko This issue now seems resolved.

**Comment by niknetniko** [comment]
> @niknetniko This issue now seems resolved.

Yep, in the end this was a Dodona issue, so no action was needed in TESTed.
