### ISSUE TITLE
Add numpy to docker container

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#288]
User request to support numpy for Python ([submission](https://dodona.ugent.be/nl/submissions/9412319/)).

Follow: https://github.com/dodona-edu/docker-images/issues/237

**Comment by niknetniko** [comment]
Do we want to add support for packages ad-hoc, or do we first want to define some kind of policy of which packages we potentially include and which we don't?

**Comment by niknetniko** [comment]
There are no concrete plans for this; besides adding support in the Docker image, there is also no support whatsoever for numpy in TESTed itself, and due to its Python-specific nature, there are no immediate plans for this.
