### ISSUE TITLE
Soorten oefeningen die ondersteund worden

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#31]
In hoofdstuk drie worden voorbeelden gegeven van soorten oefeningen die ondersteund worden door de generieke judge. Daar is op dit moment sprake van drie soorten oefeningen die zullen besproken worden, maar misschien zijn er nog extra waarvan we een voorbeeld zouden willen geven:

- batch uitvoer: enkel uitvoeren van ingediende oplossing, zonder bijkomende testgevallen
  - lezen van stdin en schrijven naar stdout: dit is het makkelijkste soort oefeningen om een generieke uitvoer voor te voorzien, maar we mogen zeker niet vergeten melden dat de generieke judge dit ook ondersteunt (eerste vier reeksen van Python oefeningen gebruiken dit)
  - opties en argumenten doorgeven: wordt gebruikt bij `bash` shell scripts in computergebruik
  - aanvullen van gegeven stuk command line: hierbij is het de bedoeling om een gegeven stuk commandolijn aan te vullen (wordt gebruikt om te leren werken op de commandolijn in computergebruik); bijvoorbeeld vul aan zodat omgekeerde string wordt teruggegeven `echo 'SPAM' | ...` (moet bv. `MAPS` uitschrijven op stdout; testgevallen bestaan telkens uit stuk commandolijn met lichte varianten, hier de string die uitgeschreven wordt op `stdin`, waar de ingediende oplossing dan moet ingevuld worden op de plaats van de drie puntjes)

**Comment by niknetniko** [comment]
(A version of) this is now part of the Dodona documentation.
