### ISSUE TITLE
Check unexpected return value

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#372]
By mistake, I used `return-raw` (with a dash) instead of `return_raw`: 
```
- statement: "sum(1, 2, 3)"
  return-raw: "6"
```
As a result, TESTed assumed that no return value was expected for this statement (this is OK, as my mistake makes TESTed think that no expected return value is set). However, TESTed also did not evaluate the actual return value, but instead completely ignored it. I would have expected that in this case, TESTed would have shown me that a value was returned, where no value was expected.

**Comment by pdawyndt** [comment]
Here's another example [submission](https://dodona.ugent.be/nl/feedbacks/1858466143/). In this case, the methode `horizontaalInvullen` is not expected to return anything, but the method returns a reference to the object on which it is called. This is accepted by TESTed, where it shouldn't.

**Comment by niknetniko** [comment]
While experimenting with #374, I encountered some issues with the concept of disallowing a return value.

The main issue is how to handle "no return value" in a language-agnostic way. For example, in Java, the compiler will enforce this if the function has a return value of "void", but not all languages do this. On the other hand, in languages such as Python and JavaScript, we cannot differentiate between "no return value" and "returning None/undefined".

**Comment by pdawyndt** [comment]
https://github.com/dodona-edu/universal-judge/issues/400
