### ISSUE TITLE
Support map with non-string keys in JavaScript

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#386]
**Suggestion**: Consider supporting maps with non-string keys in JavaScript as `Map`, where `Object` can only be used for maps with string keys.

**Rationale**: JavaScript objects (`Object`) always have string keys. As a result, TESTed currently also supports maps with string keys in JavaScript. However, TESTed also supports `Map` as a representation of maps in JavaScript, and they can have non-string keys.

**Comment by pdawyndt** [comment]
Are there any ideas on how to resolve this issue? As a use case, I would apply this for the exercise "Str8ts" which currently has two methods the now require to have `String` keys instead of the (more logical) `Number` keys.

**Comment by niknetniko** [comment]
A full solution would need two parts here I think:

- Use the ES6 `Map` as the "map" type in JavaScript by default and add an advanced type for `object`, which means more key types can be used.
- Expand the type checks to support limitations on element types for all collections, not just "maps" and "sets" as it is now.

Then, we can support `Map` with different  types of keys in the test suite in addition to `object`s.

**Comment by pdawyndt** [comment]
I would agree with this solution. As far as I can judge, this does not seem to break anything.

One issue that came to mind for later: when TESTed supports map-item access, we need to take into account that the syntax is different for `Map` and `Object` in JavaScript.
