### ISSUE TITLE
Rename "value" to "expected_value" for outputs

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#404]
We may make the difference that test suites specify the given value (`value`) for an input and the expected value (`expected_value`) for an output. This makes it clearer that outputs have an expected value as specified in the test suite and a generated value as obtained by running the main call, statement or expression.

**Comment by pdawyndt** [comment]
We can close this issue if we want to apply the "short is better than long" convention in TESTed-DSL. We also use `return` instead of `return_value`, or `stdout` instead of `standard_output`.

**Comment by niknetniko** [comment]
> We can close this issue if we want to apply the "short is better than long" convention in TESTed-DSL.

I think we do want to apply this convention here, because we should then for consistency probably also prefix a lot of other stuff (like `return`, `stdout`, `stderr`, `exit_code` with `expected`) with `expected`.
