### ISSUE TITLE
Advanced return type (tuple) - how to use?

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/universal-judge#509]
According to the [docs](https://docs.dodona.be/nl/references/tested/types/) TESTed has support for the immutable sequence `tuple`.  Does this mean I can test if my pupils have a function which properly returns tuples instead of lists?

I've tried (mimicking the [full example](https://docs.dodona.be/nl/references/tested/dsl/#volledig-voorbeeld))

```
- expression: RGB( (0,128,128) )
  return: "tuple( (255, 127, 127) )"
```

instead of
```
- expression: RGB( (0,128,128) )
  return:
  - 255
  - 127
  - 127
```

since the last example would also approve of a `list` with the values...

**Comment by niknetniko** [comment]
It seems this has been resolved, so I'll close the issue.

(A small tip: consider posting questions like this in our [Discussions](https://github.com/orgs/dodona-edu/discussions/categories/questions-vragen) in the future, this makes it more discoverable for others as well)
