### ISSUE TITLE
Report non-zero exit status (use 0 as default exit status)

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#536]
Problem: If not exit status is set (so it default to an expected exit status `0`), but a script ends with a non-zero exit status, the latter is not reported.

Solution: Report non-zero exit status if no exit status is set explicitly (as a default).

Example: https://dodona.be/nl/feedbacks/928249530/ (all testcases in "Track" unit)
Example: https://dodona.be/nl/feedbacks/546274247/ (testcase #11)

**Comment by niknetniko** [comment]
This default was chosen because some languages also set the exit code to non-zero when an exception occurs and this could then be confusing for students as there would be feedback about an exit code. As such, the default of ignoring it unless explicitly stated makes sense to me.

**Comment by pdawyndt** [comment]
Would there be a way to only report a non-zero exit status generated by a submission, when a zero exit status is expected? Setting an expected zero exit status in the test plan would mean that the exit status is always reported in the feedback table, even if the submission also exits with status zero. This would bring a lot of clutter to the feedback table for the students.

**Comment by niknetniko** [comment]
> Would there be a way to only report a non-zero exit status generated by a submission, when a zero exit status is expected? Setting an expected zero exit status in the test plan would mean that the exit status is always reported in the feedback table, even if the submission also exits with status zero. This would bring a lot of clutter to the feedback table for the students.

As I recall, that should be how it currently behaves. If you explicitly set an exit code check, the feedback is only shown if the generated code is non-zero or wrong (so erroneous zero exit code feedback is shown, in addition to feedback whenever the exit code is non-zero)

**Comment by pdawyndt** [comment]
> As I recall, that should be how it currently behaves. If you explicitly set an exit code check, the feedback is only shown if the generated code is non-zero or wrong (so erroneous zero exit code feedback is shown, in addition to feedback whenever the exit code is non-zero)

I can confirm that this is indeed how TESTed behaves: if a zero exit code is set explicitly and execution of the submitted solution exit with status zero, no exit status reporting is done in the feedback table. But a non-zero exit status is reported in this case. This will work, but requires us to update the test suites all bash shell script exercises (but a simple search-and-replace did the job for the exercise that I checked).

**Comment by pdawyndt** [comment]
All bash shell scripting exercises supported by TESTed have been modified accordingly.
