### ISSUE TITLE
Error when evaluating Java exercise

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#68]
https://dodona.ugent.be/nl/submissions/5918478/

Some compiler errors seem to be caught, but there is still an error somewhere causing an internal error.

**Comment by bsels** [comment]
Because of some reason, that I don't known, the compilation process terminate sometimes successful, even if the compilation failed. Therefor to code that searches for the mainfile doesn't find any and returns an `IndexError`.
