### ISSUE TITLE
Rewrite Python stack traces

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#72]
Python stack traces need some cleanup and augmentation:

- [x] references to lines outside `submission.py` should be removed (Python judge has code to do so)
- [x] references to lines  `submission.py` could be linked to the code (Python judge has code to do so)
- [x] how on earth did the message (`Fout met boodschap: '8'`) in the example stack trace below get translated?

Example: [submission 5947797])(https://dodona.ugent.be/nl/submissions/5947797/)

![image](https://user-images.githubusercontent.com/5736113/95981941-c366c780-0e1f-11eb-9b26-ec98b76f5393.png)

**Comment by bsels** [comment]
The message `Fout met boodschap: '8'` cames from `KeyError: '8'`.
The solution is to add the errorname to to message.

**Comment by pdawyndt** [comment]
I would also suggest to drop the `Fout met boodschap`.
